
/**
 * This file is generated by Sencha Cmd and should NOT be edited.  It is 
 * provided to support globbing requires, custom xtypes, and other 
 * metadata-driven class system features 
 */
Ext.Loader.addClassPathMappings({
  "Ext": "ext/src",
  " Ext.Msg": "ext/src/window/MessageBox.js",
  "playground.Application": "app/application.js",
  "playground": "app"
});
Ext.ClassManager.addNameAlternateMappings({
  "Ext.ux.grid.filter.DateTimeFilter": [],
  "Ext.ux.statusbar.ValidationStatus": [],
  "Ext.ux.TabCloseMenu": [],
  "Ext.ux.BoxReorderer": [],
  "Ext.ux.GroupTabRenderer": [],
  "Ext.ux.grid.filter.NumericFilter": [],
  "Ext.ux.ProgressBarPager": [],
  "Ext.ux.SlidingPager": [],
  "playground.view.Main": [],
  "Ext.ux.ajax.JsonSimlet": [],
  "Ext.ux.grid.filter.BooleanFilter": [],
  "Ext.ux.PreviewPlugin": [],
  "Ext.ux.event.Driver": [],
  "Ext.ux.data.PagingMemoryProxy": [
    "Ext.data.PagingMemoryProxy"
  ],
  "Ext.ux.TreePicker": [],
  "Ext.ux.grid.filter.StringFilter": [],
  "Ext.ux.event.RecorderManager": [],
  "Ext.ux.DataTip": [],
  "Ext.ux.dd.CellFieldDropZone": [],
  "Ext.ux.grid.menu.RangeMenu": [],
  "Ext.ux.Spotlight": [],
  "Ext.ux.IFrame": [],
  "Ext.ux.ajax.DataSimlet": [],
  "Ext.ux.DataView.Animated": [],
  "Ext.ux.TabScrollerMenu": [],
  "playground.controller.Main": [],
  "Ext.ux.ajax.SimXhr": [],
  "Ext.ux.grid.TransformGrid": [],
  "Ext.ux.grid.menu.ListMenu": [],
  "Ext.ux.dd.PanelFieldDragZone": [],
  "Ext.ux.event.Maker": [],
  "Ext.ux.ajax.SimManager": [],
  "Ext.ux.form.SearchField": [],
  "Ext.ux.grid.filter.ListFilter": [],
  "playground.view.Viewport": [],
  "Ext.ux.GroupTabPanel": [],
  "Ext.ux.LiveSearchGridPanel": [],
  "Ext.ux.RowExpander": [],
  "Ext.ux.grid.filter.DateFilter": [],
  "Ext.ux.grid.FiltersFeature": [],
  "Ext.ux.layout.Center": [],
  "Ext.ux.FieldReplicator": [],
  "Ext.ux.GMapPanel": [],
  "playground.Application": [],
  "Ext.ux.event.Recorder": [],
  "Ext.ux.form.MultiSelect": [
    "Ext.ux.Multiselect"
  ],
  "Ext.ux.DataView.Draggable": [],
  "Ext.ux.TabReorderer": [],
  "Ext.ux.ToolbarDroppable": [],
  "Ext.ux.statusbar.StatusBar": [
    "Ext.ux.StatusBar"
  ],
  "Ext.ux.DataView.DragSelector": [],
  "Ext.ux.event.Player": [],
  "Ext.ux.CellDragDrop": [],
  "Ext.ux.DataView.LabelEditor": [],
  "Ext.ux.ajax.Simlet": [],
  "Ext.ux.grid.filter.Filter": [],
  "Ext.ux.form.ItemSelector": [
    "Ext.ux.ItemSelector"
  ],
  "Ext.ux.ajax.XmlSimlet": []
});
Ext.ClassManager.addNameAliasMappings({
  "Ext.ux.grid.filter.DateTimeFilter": [
    "gridfilter.datetime"
  ],
  "Ext.ux.statusbar.ValidationStatus": [],
  "Ext.ux.TabCloseMenu": [
    "plugin.tabclosemenu"
  ],
  "Ext.ux.BoxReorderer": [],
  "Ext.ux.GroupTabRenderer": [
    "plugin.grouptabrenderer"
  ],
  "Ext.ux.grid.filter.NumericFilter": [
    "gridfilter.numeric"
  ],
  "Ext.ux.ProgressBarPager": [],
  "Ext.ux.SlidingPager": [],
  "playground.view.Main": [
    "widget.app-main"
  ],
  "Ext.ux.ajax.JsonSimlet": [
    "simlet.json"
  ],
  "Ext.ux.grid.filter.BooleanFilter": [
    "gridfilter.boolean"
  ],
  "Ext.ux.PreviewPlugin": [
    "plugin.preview"
  ],
  "Ext.ux.event.Driver": [],
  "Ext.ux.data.PagingMemoryProxy": [
    "proxy.pagingmemory"
  ],
  "Ext.ux.TreePicker": [
    "widget.treepicker"
  ],
  "Ext.ux.grid.filter.StringFilter": [
    "gridfilter.string"
  ],
  "Ext.ux.event.RecorderManager": [
    "widget.eventrecordermanager"
  ],
  "Ext.ux.DataTip": [
    "plugin.datatip"
  ],
  "Ext.ux.dd.CellFieldDropZone": [],
  "Ext.ux.grid.menu.RangeMenu": [],
  "Ext.ux.Spotlight": [],
  "Ext.ux.IFrame": [
    "widget.uxiframe"
  ],
  "Ext.ux.ajax.DataSimlet": [],
  "Ext.ux.DataView.Animated": [],
  "Ext.ux.TabScrollerMenu": [
    "plugin.tabscrollermenu"
  ],
  "playground.controller.Main": [],
  "Ext.ux.ajax.SimXhr": [],
  "Ext.ux.grid.TransformGrid": [],
  "Ext.ux.grid.menu.ListMenu": [],
  "Ext.ux.dd.PanelFieldDragZone": [],
  "Ext.ux.event.Maker": [],
  "Ext.ux.ajax.SimManager": [],
  "Ext.ux.form.SearchField": [
    "widget.searchfield"
  ],
  "Ext.ux.grid.filter.ListFilter": [
    "gridfilter.list"
  ],
  "playground.view.Viewport": [],
  "Ext.ux.GroupTabPanel": [
    "widget.grouptabpanel"
  ],
  "Ext.ux.LiveSearchGridPanel": [],
  "Ext.ux.RowExpander": [],
  "Ext.ux.grid.filter.DateFilter": [
    "gridfilter.date"
  ],
  "Ext.ux.grid.FiltersFeature": [
    "feature.filters"
  ],
  "Ext.ux.layout.Center": [
    "layout.ux.center"
  ],
  "Ext.ux.FieldReplicator": [],
  "Ext.ux.GMapPanel": [
    "widget.gmappanel"
  ],
  "playground.Application": [],
  "Ext.ux.event.Recorder": [],
  "Ext.ux.form.MultiSelect": [
    "widget.multiselect",
    "widget.multiselectfield"
  ],
  "Ext.ux.DataView.Draggable": [],
  "Ext.ux.TabReorderer": [],
  "Ext.ux.ToolbarDroppable": [],
  "Ext.ux.statusbar.StatusBar": [
    "widget.statusbar"
  ],
  "Ext.ux.DataView.DragSelector": [],
  "Ext.ux.event.Player": [],
  "Ext.ux.CellDragDrop": [
    "plugin.celldragdrop"
  ],
  "Ext.ux.DataView.LabelEditor": [],
  "Ext.ux.ajax.Simlet": [
    "simlet.basic"
  ],
  "Ext.ux.grid.filter.Filter": [],
  "Ext.ux.form.ItemSelector": [
    "widget.itemselector",
    "widget.itemselectorfield"
  ],
  "Ext.ux.ajax.XmlSimlet": [
    "simlet.xml"
  ]
});
